"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import {
  FileText,
  FileCheck,
  FolderArchive,
  Download,
  Loader2,
  RotateCcw,
  AlertTriangle,
  Ban,
  ArrowLeft,
  Layers,
  ArrowUpRight,
} from "lucide-react";
import type { GeneralData, CoverPage } from "../types";
import { Button } from "@/components/ui/button";
import {
  getFileName,
  formatDisplayCode,
  formatMesAno,
} from "../hooks/helpers";
import type { CoverTitleMode } from "@/lib/cover-utils";
import { LABEL_CLASS } from "../constants";

interface GeneratedDownload {
  fileName: string;
  url: string;
  kind: "odt" | "pdf" | "zip";
}

interface GenerateResponse {
  files: {
    odt: { name: string; data: string };
    pdf: { name: string; data: string } | null;
    zip: { name: string; data: string };
  };
  pdfError?: string;
  error?: string;
}

const CHECKLIST_ITEMS = [
  "Abrir ODT no LibreOffice",
  "Conferir todas as capas",
  "Conferir ordem das paginas",
  "Conferir orgao e secretaria",
  "Conferir nome da obra",
  "Conferir fase do projeto",
  "Conferir mes/ano",
  "Conferir codigo exibido",
  "Conferir titulo, tomo e volume de cada capa",
  "Conferir rodape e propriedades do documento",
  "Conferir PDF gerado (se disponivel)",
];

interface StepResultProps {
  generalData: GeneralData;
  pages: CoverPage[];
  templateFields: string[];
  coverTitleMode: CoverTitleMode;
  onBack: () => void;
  onReset: () => void;
  projectId?: string;
}

/**
 * Coleta as disciplinas unicas das capas para pre-preencher o gerador de
 * separatrizes. Usa o campo de disciplina separado quando o template tem um;
 * caso contrario, as linhas do texto da capa (ignorando a 1a linha quando ela
 * e o titulo do volume).
 */
function collectDisciplines(
  pages: CoverPage[],
  templateFields: string[],
  coverTitleMode: CoverTitleMode
): string[] {
  const hasSeparateDiscipline = templateFields.includes("DISCIPLINA");
  const seen = new Set<string>();
  const result: string[] = [];

  for (const page of pages) {
    const source = hasSeparateDiscipline ? page.disciplina : page.tituloCapa;
    let lines = source
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean);
    if (!hasSeparateDiscipline && coverTitleMode === "volume-title-items") {
      lines = lines.slice(1);
    }
    for (const line of lines) {
      if (!seen.has(line)) {
        seen.add(line);
        result.push(line);
      }
    }
  }

  return result;
}

function base64ToObjectUrl(base64: string, mimeType: string) {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);

  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }

  return URL.createObjectURL(new Blob([bytes], { type: mimeType }));
}

export function StepResult({
  generalData,
  pages,
  templateFields,
  coverTitleMode,
  onBack,
  onReset,
  projectId,
}: StepResultProps) {
  const [checkedItems, setCheckedItems] = useState<Set<number>>(new Set());
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [downloads, setDownloads] = useState<GeneratedDownload[]>([]);
  const [pdfError, setPdfError] = useState<string | null>(null);
  const hasAutoGenerated = useRef(false);

  const { codigoInterno, codigoExibido, siglaArquivo, revisao } = generalData;
  const sigla = siglaArquivo || "";
  const rev = revisao || "r";
  const code = codigoInterno || "codigo";
  const displayCode = codigoExibido || formatDisplayCode(codigoInterno);
  const showSecretaria =
    templateFields.length === 0 || templateFields.includes("SECRETARIA");
  const hasSeparateDiscipline = templateFields.includes("DISCIPLINA");
  const titleColumn =
    coverTitleMode === "volume-title-items"
      ? "Titulo do volume e itens"
      : hasSeparateDiscipline
        ? "Titulo fixo"
        : "Texto da capa / disciplinas";

  const disciplinas = collectDisciplines(pages, templateFields, coverTitleMode);
  const separatrizHref =
    disciplinas.length > 0
      ? `/separatrizes?d=${encodeURIComponent(disciplinas.join("|"))}` +
        `&codigo=${encodeURIComponent(codigoInterno)}` +
        `&rev=${encodeURIComponent(revisao)}`
      : "/separatrizes";

  function toggleItem(index: number) {
    setCheckedItems((prev) => {
      const next = new Set(prev);
      if (next.has(index)) {
        next.delete(index);
      } else {
        next.add(index);
      }
      return next;
    });
  }

  async function handleGenerate() {
    setGenerating(true);
    setError(null);
    setPdfError(null);

    try {
      const response = await fetch("/api/capas/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ generalData, pages, projectId }),
      });

      if (!response.ok) {
        const payload = (await response.json().catch(() => null)) as { error?: string } | null;
        throw new Error(payload?.error ?? "Nao foi possivel gerar os arquivos.");
      }

      const payload = (await response.json()) as GenerateResponse;

      setDownloads((prev) => {
        prev.forEach((d) => URL.revokeObjectURL(d.url));
        return [
          {
            fileName: payload.files.odt.name,
            kind: "odt" as const,
            url: base64ToObjectUrl(payload.files.odt.data, "application/vnd.oasis.opendocument.text"),
          },
          payload.files.pdf
            ? {
                fileName: payload.files.pdf.name,
                kind: "pdf" as const,
                url: base64ToObjectUrl(payload.files.pdf.data, "application/pdf"),
              }
            : null,
          {
            fileName: payload.files.zip.name,
            kind: "zip" as const,
            url: base64ToObjectUrl(payload.files.zip.data, "application/zip"),
          },
        ].filter((d): d is GeneratedDownload => Boolean(d));
      });

      if (payload.pdfError) setPdfError(payload.pdfError);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erro ao gerar arquivos");
    } finally {
      setGenerating(false);
    }
  }

  // Gera automaticamente ao entrar na etapa: o usuario ja confirmou tudo na previa.
  useEffect(() => {
    if (hasAutoGenerated.current) return;
    hasAutoGenerated.current = true;
    void handleGenerate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const hasPdf = downloads.some((d) => d.kind === "pdf");

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-medium tracking-[-0.01em]">Resultado</h2>
        <p className="mt-1 text-sm text-muted-foreground">
          Os arquivos sao gerados automaticamente. O ODT sempre fica disponivel;
          o PDF depende do LibreOffice no servidor.
        </p>
      </div>

      {error && (
        <div
          role="alert"
          aria-live="assertive"
          className="flex items-start gap-2 rounded-md border border-destructive/30 bg-destructive/8 p-3 text-sm text-destructive"
        >
          <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      <div className="flex items-center justify-between">
        <Button variant="outline" onClick={onBack} disabled={generating}>
          <ArrowLeft className="mr-1.5 h-4 w-4" />
          Voltar a previa
        </Button>
        <div className="flex items-center gap-2">
          <Button variant="outline" onClick={onReset} disabled={generating}>
            <RotateCcw className="mr-1.5 h-4 w-4" />
            Nova geracao
          </Button>
          <Button
            variant="outline"
            onClick={handleGenerate}
            disabled={generating}
          >
            {generating ? (
              <Loader2 className="mr-1.5 h-4 w-4 animate-spin" />
            ) : (
              <Download className="mr-1.5 h-4 w-4" />
            )}
            {generating
              ? "Gerando..."
              : downloads.length > 0
                ? "Gerar novamente"
                : "Gerar arquivos"}
          </Button>
        </div>
      </div>

      {generating && downloads.length === 0 && (
        <div className="flex items-center justify-center gap-2 rounded-md border border-dashed border-border bg-card p-10 text-sm text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin" />
          Gerando {pages.length} capa(s)...
        </div>
      )}

      {downloads.length > 0 && (
        <div className="grid gap-3 sm:grid-cols-3">
          <DownloadCard
            icon={FileText}
            label="ODT"
            fileName={getFileName(code, sigla, rev, "odt")}
            description="Documento editavel"
            download={downloads.find((d) => d.kind === "odt")}
          />
          <DownloadCard
            icon={FileCheck}
            label="PDF"
            fileName={getFileName(code, sigla, rev, "pdf")}
            description={
              hasPdf
                ? "Arquivo final para envio"
                : pdfError
                  ? `PDF indisponivel: ${pdfError}`
                  : "PDF indisponivel (conversor nao configurado)"
            }
            download={downloads.find((d) => d.kind === "pdf")}
            unavailable={!hasPdf}
          />
          <DownloadCard
            icon={FolderArchive}
            label="ZIP"
            fileName={getFileName(code, sigla, rev, "zip")}
            description={hasPdf ? "ODT + PDF no mesmo pacote" : "Apenas ODT (PDF indisponivel)"}
            download={downloads.find((d) => d.kind === "zip")}
            primary
          />
        </div>
      )}

      {/* Atalho para separar as disciplinas dentro do volume */}
      <div className="flex flex-col gap-3 rounded-md border border-border bg-card p-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-start gap-3">
          <div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-primary/25 bg-primary/10">
            <Layers className="h-4 w-4 text-primary" />
          </div>
          <div>
            <p className="text-sm font-medium">Folhas separatrizes</p>
            <p className="mt-0.5 text-xs text-muted-foreground">
              {disciplinas.length > 0
                ? `Gere uma folha de separacao por disciplina (${disciplinas.length}) para dividir o volume.`
                : "Gere folhas de separacao de disciplinas para dividir o volume."}
            </p>
          </div>
        </div>
        <Button variant="outline" asChild className="shrink-0">
          <Link href={separatrizHref}>
            Gerar separatrizes
            <ArrowUpRight className="ml-1.5 h-4 w-4" />
          </Link>
        </Button>
      </div>

      {/* Resumo do que foi gerado */}
      <div className="grid gap-4 sm:grid-cols-2">
        <div className="rounded-md border border-border bg-card p-4 space-y-3">
          <h3 className={LABEL_CLASS}>
            Totais
          </h3>
          <div className="space-y-1">
            <p className="text-sm">
              Total de capas:{" "}
              <span className="font-semibold tabular-nums">{pages.length}</span>
            </p>
            <p className="text-sm">
              Codigo: <span className="font-semibold">{displayCode || "-"}</span>
            </p>
            {generalData.mes && (
              <p className="text-sm">
                Periodo:{" "}
                <span className="font-semibold">
                  {formatMesAno(generalData.mes, generalData.ano)}
                </span>
              </p>
            )}
          </div>
        </div>

        <div className="rounded-md border border-border bg-card p-4 space-y-3">
          <h3 className={LABEL_CLASS}>
            Dados do Projeto
          </h3>
          <div className="grid gap-1.5 text-sm">
            <div>
              <span className="text-muted-foreground">Orgao: </span>
              <span className="font-medium">{generalData.orgao || "-"}</span>
            </div>
            {showSecretaria && (
              <div>
                <span className="text-muted-foreground">Secretaria: </span>
                <span className="font-medium">{generalData.secretaria || "-"}</span>
              </div>
            )}
            <div>
              <span className="text-muted-foreground">Obra: </span>
              <span className="font-medium">{generalData.nomeObra || "-"}</span>
            </div>
            <div>
              <span className="text-muted-foreground">Fase: </span>
              <span className="font-medium">{generalData.fase || "-"}</span>
            </div>
          </div>
        </div>
      </div>

      <div className="overflow-hidden rounded-md border border-border">
        <div className="flex items-center justify-between border-b border-border bg-muted px-5 py-3">
          <span className={LABEL_CLASS}>
            Lista de capas ({pages.length})
          </span>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full caption-bottom text-sm">
            <thead>
              <tr className="border-b border-border">
                <th className="h-10 px-4 text-left font-mono text-xs text-muted-foreground w-16">
                  Pag.
                </th>
                <th className="h-10 px-4 text-left font-mono text-xs text-muted-foreground">
                  {titleColumn}
                </th>
                {hasSeparateDiscipline && (
                  <th className="h-10 px-4 text-left font-mono text-xs text-muted-foreground w-40">
                    Disciplinas
                  </th>
                )}
                <th className="h-10 px-4 text-left font-mono text-xs text-muted-foreground w-24">
                  Tomo
                </th>
                <th className="h-10 px-4 text-left font-mono text-xs text-muted-foreground w-20">
                  Volume
                </th>
              </tr>
            </thead>
            <tbody>
              {pages.map((page) => (
                <tr key={page.id} className="border-b border-border">
                  <td className="p-4 font-mono text-xs tabular-nums text-muted-foreground">
                    {String(page.pageNumber).padStart(2, "0")}
                  </td>
                  <td className="p-4 text-sm whitespace-pre-wrap">{page.tituloCapa}</td>
                  {hasSeparateDiscipline && (
                    <td className="p-4 text-xs whitespace-pre-wrap text-muted-foreground">
                      {page.disciplina || "-"}
                    </td>
                  )}
                  <td className="p-4 text-xs">{page.tomo || "-"}</td>
                  <td className="p-4 text-xs">{page.volume}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="overflow-hidden rounded-md border border-border bg-card">
        <div className="flex items-center justify-between border-b border-border px-5 py-3">
          <div className="flex items-center gap-2">
            <span className={LABEL_CLASS}>
              Checklist de conferencia
            </span>
            <span className="font-mono text-xs text-muted-foreground">(pos-download)</span>
          </div>
          <span className="font-mono text-xs tabular-nums text-muted-foreground">
            {checkedItems.size}/{CHECKLIST_ITEMS.length}
          </span>
        </div>
        <div className="divide-y divide-border">
          {CHECKLIST_ITEMS.map((item, index) => (
            <label
              key={index}
              className="flex items-center gap-3 px-5 py-3 cursor-pointer hover:bg-muted/30 transition-colors"
            >
              <input
                type="checkbox"
                checked={checkedItems.has(index)}
                onChange={() => toggleItem(index)}
                className="h-4 w-4 accent-primary"
              />
              <span
                className={`text-sm ${
                  checkedItems.has(index)
                    ? "line-through decoration-muted-foreground/40"
                    : ""
                }`}
              >
                {item}
              </span>
            </label>
          ))}
        </div>
      </div>
    </div>
  );
}

function DownloadCard({
  icon: Icon,
  label,
  fileName,
  description,
  download,
  unavailable,
  primary,
}: {
  icon: typeof FileText;
  label: string;
  fileName: string;
  description: string;
  download?: GeneratedDownload;
  unavailable?: boolean;
  primary?: boolean;
}) {
  return (
    <div
      className={`rounded-md border bg-card p-4 text-center ${
        primary ? "border-primary/40 bg-primary/[0.04]" : "border-border"
      }`}
    >
      <div className={`mx-auto mb-2 flex h-10 w-10 items-center justify-center rounded-md border ${
        unavailable ? "border-muted-foreground/25 bg-muted" : "border-primary/25 bg-primary/10"
      }`}>
        <Icon className={`h-4 w-4 ${unavailable ? "text-muted-foreground" : "text-primary"}`} />
      </div>
      <p className={LABEL_CLASS}>
        {label}
      </p>
      <p className="mt-1 font-mono text-xs text-muted-foreground break-all">
        {fileName}
      </p>
      <p className="mt-2 text-xs text-muted-foreground">{description}</p>
      {download ? (
        <Button
          className="mt-4 w-full"
          variant={primary ? "default" : "outline"}
          asChild
        >
          <a href={download.url} download={download.fileName}>
            <Download className="mr-1.5 h-4 w-4" />
            Baixar {label}
          </a>
        </Button>
      ) : (
        <Button
          className="mt-4 w-full"
          variant="outline"
          disabled
        >
          <Ban className="mr-1.5 h-4 w-4" />
          Indisponivel
        </Button>
      )}
    </div>
  );
}
